/**
 * KGEM 2026: Universal Map Link Factory
 * 🔥 FIX: Coordinate-based navigation for auto-generated spots.
 * Uses lat/lng directly when available, with name as fallback label only.
 */

export type MapType = 'naver' | 'kakao' | 'google';

interface Destination {
    lat?: number;
    lng?: number;
    name: string;      // Korean name (for Naver/Kakao)
    enName?: string;    // English/Japanese name (for Google)
}

export type MapMode = 'search' | 'directions';

/**
 * Determines if a spot name is a "real" searchable POI name or an auto-generated placeholder.
 * Auto-generated names follow patterns like:
 *   KO: "강남 필승 전략 - 서울 1", "서울 1인분 삼겹살 1", "서울 시크릿 티 투어 1"
 *   EN: "Gangnam Strategy - Seoul 1", "Seoul Solo BBQ Spot 1", "Seoul Secret Tea Tour 1"
 *   JA: "江南必勝戦略 - ソウル 1", "ソウル 1人前サムギョプサル 1", "ソウル シークレットティーツアー 1"
 */
export const isRealPOI = (name: string): boolean => {
    const trimmedName = name.trim();

    // 2026 Premium Placeholder Patterns
    if (/\[Premium\]/i.test(trimmedName)) return false;
    if (/\(Premium\)/i.test(trimmedName)) return false;
    // Detect Emoji (Universal for 🚀, 🥩, 🍵, etc.)
    if (/[\u{1F300}-\u{1F9FF}]/u.test(trimmedName)) return false;
    // Detect "#" digit pattern (e.g., "히든 스팟 #1", "Hidden Spot #1")
    if (/(히든\s*스팟|Hidden\s*Spot|隠れスポット|Spot)\s*#\d+/i.test(trimmedName)) return false;

    // Korean auto-generated patterns
    if (/[-–]\s*(서울|부산|제주|대구|대전|광주|인천|울산|세종|경기|강원|충북|충남|전북|전남|경북|경남|기타)\s*\d+/i.test(trimmedName)) return false;
    if (/\b(서울|부산|제주|대구|대전|광주|인천)\s+.+\s+\d+\s*$/.test(trimmedName)) return false;  // "서울 1인분 삼겹살 1"
    if (/\b(전략|투어|삼겹살|티\s*투어)\s*[-–]?\s*\w*\s*\d+\s*$/i.test(trimmedName)) return false;

    // English auto-generated patterns
    if (/\b(Strategy|Tour|BBQ|Spot)\s*[-–]?\s*\w*\s*\d+\s*$/i.test(trimmedName)) return false;  // "Gangnam Strategy - Seoul 1", "Seoul Solo BBQ Spot 1"
    if (/\bSolo\s+BBQ\s+Spot\s+\d+/i.test(trimmedName)) return false;
    if (/\bSecret\s+Tea\s+Tour\s+\d+/i.test(trimmedName)) return false;
    if (/\bGangnam\s+Strategy\s+/i.test(trimmedName) && /\d+\s*$/.test(trimmedName)) return false;

    // Japanese auto-generated patterns
    if (/[-–]\s*(ソウル|プサン|チェジュ|テグ|テジョン|クァンジュ|インチョン)\s*\d+/i.test(trimmedName)) return false;
    if (/(サムギョプサル|ティーツアー|シークレットティーツアー|必勝戦略)\s*\d+/i.test(trimmedName)) return false;
    if (/ソウル\s+.+\s+\d+\s*$/.test(trimmedName)) return false;  // "ソウル 1人前サムギョプサル 1"

    // Universal: secret menu / owner tip placeholders
    if (/비밀\s*메뉴\s*\d+|Secret\s*Menu\s*\d+|裏メニュー\s*\d+/i.test(trimmedName)) return false;

    return true;
};

// Convenience: inverse of isRealPOI for readability
export const isAutoGenerated = (name: string): boolean => !isRealPOI(name);

export const getMapScheme = (dest: Destination, type: MapType, isAndroid: boolean, language: string, mode: MapMode = 'search'): string => {
    const { lat, lng, name, enName } = dest;
    const hasCoords = lat !== undefined && lng !== undefined && lat !== 0 && lng !== 0;

    // Always use the actual spot name for map search - no more fallbacks
    let hybridName = language === 'ko' ? name : (enName || name);

    const encodedName = encodeURIComponent(hybridName);
    const naverLang = language === 'ja' ? 'ja' : language === 'ko' ? 'ko' : language === 'zh' ? 'zh' : 'en';

    // Always use text search with the real name
    const useCoords = hasCoords;

    switch (type) {
        case 'naver':
            if (isAndroid) {
                const intentScheme = `intent://route/public?dlat=${lat}&dlng=${lng}&dname=${encodedName}&appname=KGem#Intent;scheme=nmap;package=com.nhn.android.nmap;S.browser_fallback_url=${encodeURIComponent(getWebFallbackUrl(dest, 'naver', language, mode))};end`;
                return intentScheme;
            }
            if (window.navigator.userAgent.match(/iphone|ipad|ipod/i)) {
                // iOS Scheme: nmap://route/public
                return mode === 'search'
                    ? `nmap://place?lat=${lat}&lng=${lng}&name=${encodedName}&appname=com.kgem.app`
                    : `nmap://route/public?dlat=${lat}&dlng=${lng}&dname=${encodedName}&appname=com.kgem.app`;
            }
            // PC/Fallback Web
            if (useCoords) {
                return mode === 'search'
                    ? `https://map.naver.com/v5/search/${encodedName}?c=${lng},${lat},15,0,0,0,dh&lang=${naverLang}`
                    : `https://map.naver.com/p/directions/-/${lng},${lat},${encodedName},,-/transit?lang=${naverLang}`;
            }
            return mode === 'search'
                ? `https://map.naver.com/v5/search/${encodedName}/?lang=${naverLang}`
                : `https://map.naver.com/p/directions/-/${lng},${lat},${encodedName},,-/transit?lang=${naverLang}`;

        case 'kakao':
            // Kakao always works well with coordinates
            if (isAndroid) {
                return mode === 'search'
                    ? `kakaomap://look?p=${lat},${lng}`
                    : `kakaomap://route?ep=${lat},${lng}&by=PUBLICTRANSIT`;
            }
            return mode === 'search'
                ? `kakaomap://look?p=${lat},${lng}`
                : `kakaomap://route?ep=${lat},${lng}&by=PUBLICTRANSIT`;

        case 'google':
        default:
            const googleTlds: { [key: string]: string } = { en: 'com', ja: 'co.jp', ko: 'ko.kr', zh: 'com' };
            const tld = googleTlds[language] || 'com';
            const langParam = language === 'ja' ? 'ja' : language === 'zh' ? 'zh-CN' : 'en';
            const lrParam = language === 'ja' ? 'lang_ja' : language === 'zh' ? 'lang_zh-CN' : 'lang_en';

            let webUrl = "";

            if (useCoords && hasCoords) {
                // 🔥 Core Fix: Use coordinates for Google Maps when the name is auto-generated
                if (mode === 'directions') {
                    webUrl = `https://maps.google.${tld}/maps/dir/?api=1&destination=${lat},${lng}&travelmode=transit&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
                } else {
                    webUrl = `https://www.google.${tld}/maps/search/?api=1&query=${lat},${lng}&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
                }
            } else {
                const googleQuery = language === 'ko' ? name : (enName || name);
                if (mode === 'directions') {
                    webUrl = `https://maps.google.${tld}/maps/dir/?api=1&destination=${encodeURIComponent(googleQuery)}&travelmode=transit&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
                } else {
                    webUrl = `https://www.google.${tld}/maps/search/?api=1&query=${encodeURIComponent(googleQuery)}&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
                }
            }

            if (isAndroid && language !== 'ko') {
                return `intent://${webUrl.replace('https://', '')}#Intent;scheme=https;action=android.intent.action.VIEW;category=android.intent.category.BROWSABLE;package=com.android.chrome;S.browser_fallback_url=${encodeURIComponent(webUrl)};end`;
            }
            return webUrl;
    }
};

export const getWebFallbackUrl = (dest: Destination, type: MapType, language: string, mode: MapMode = 'search'): string => {
    const { lat, lng, name, enName } = dest;
    const hasCoords = lat !== undefined && lng !== undefined && lat !== 0 && lng !== 0;
    const useCoords = hasCoords;

    const naverLang = language === 'ja' ? 'ja' : language === 'ko' ? 'ko' : language === 'zh' ? 'zh' : 'en';

    // Always use the actual spot name - no more fake fallbacks
    let displayName = language === 'ko' ? name : (enName || name);

    const encodedName = encodeURIComponent(displayName);

    if (type === 'naver') {
        if (useCoords) {
            return mode === 'search'
                ? `https://map.naver.com/v5/search/${encodedName}?c=${lng},${lat},15,0,0,0,dh&lang=${naverLang}`
                : `https://map.naver.com/p/directions/-/${lng},${lat},${encodedName},,-/transit?lang=${naverLang}`;
        }
        return mode === 'search'
            ? `https://map.naver.com/v5/search/${encodedName}/?lang=${naverLang}`
            : `https://map.naver.com/p/directions/-/${lng},${lat},${encodedName},,-/transit?lang=${naverLang}`;
    }

    if (type === 'kakao') {
        if (useCoords && hasCoords) {
            return mode === 'search'
                ? `https://map.kakao.com/link/map/${encodedName},${lat},${lng}`
                : `https://map.kakao.com/link/to/${encodedName},${lat},${lng}`;
        }
        return mode === 'search'
            ? `https://map.kakao.com/search?q=${encodedName}`
            : `https://map.kakao.com/link/to/${encodedName},${lat},${lng}`;
    }

    // Google
    const googleTlds: { [key: string]: string } = { en: 'com', ja: 'co.jp', ko: 'ko.kr', zh: 'com' };
    const tld = googleTlds[language] || 'com';
    const langParam = language === 'ja' ? 'ja' : language === 'zh' ? 'zh-CN' : 'en';
    const lrParam = language === 'ja' ? 'lang_ja' : language === 'zh' ? 'lang_zh-CN' : 'lang_en';

    if (useCoords && hasCoords) {
        if (mode === 'directions') {
            return `https://maps.google.${tld}/maps/dir/?api=1&destination=${lat},${lng}&travelmode=transit&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
        }
        return `https://www.google.${tld}/maps/search/?api=1&query=${lat},${lng}&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
    }

    const googleQuery = language === 'ko' ? name : (enName || name);
    if (mode === 'directions') {
        return `https://maps.google.${tld}/maps/dir/?api=1&destination=${encodeURIComponent(googleQuery)}&travelmode=transit&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
    }
    return `https://www.google.${tld}/maps/search/?api=1&query=${encodeURIComponent(googleQuery)}&hl=${langParam}&lr=${lrParam}&set_language=${langParam}`;
};

export const getStoreUrl = (type: MapType, isIOS: boolean): string => {
    if (type === 'naver') {
        return isIOS ? 'https://apps.apple.com/kr/app/id311867728' : 'market://details?id=com.nhn.android.nmap';
    }
    if (type === 'kakao') {
        return isIOS ? 'https://apps.apple.com/kr/app/id304608425' : 'market://details?id=net.daum.android.map';
    }
    return '';
};
